### ISSUE TITLE
Handle boolean array arguments better

### ISSUE THREAD

**Issue by Qix-** [zeit/arg#11]
This is justified since `Boolean` types already get a bit of special treatment.

In the case I want multiple levels of verbosity, for example, the following should work:

```javascript
// ./my-program -vvvv

const arg = require('arg');

const args = arg({
    '-v': [Boolean]
});

console.log(args);
/*
    {
        _: [],
        '-v': 4
    }
*/
```

Currently, you have to do `-v -v -v -v` separately, and in turn you get `[true, true, true, true]`, which isn't exactly elegant.

**Comment by pacocoursey** [comment]
I have completed this, but I could use a few more use-cases to ensure it serves the correct purpose.

Using your example above, should `./my-program -vvvv -v` output `'-v': 5`?

What if the flag `'-vvv'` exists? Should the following return case 1 or case 2?

```js
// ./my-program -vvv -vvv

const args = arg({
    '-vvv': Boolean,
    '-v': [Boolean]
});

console.log(args);

/*
    {
        _: [],

        // case 1...
        '-vvv': true,
        '-v': 3

        // or case 2...
        '-vvv': true
    }
*/
```

Don't want to miss an edge case 😅

**Comment by Qix-** [comment]
> Using your example above, should `./my-program -vvvv -v` output `'-v': 5`?

Yes. :)

> What if the flag `'-vvv'` exists?

It won't; it's one of `arg`'s few opinions. Single-dash options are only single letters - we have #4 open to enforce this as the example snippet you provided _should_ throw an error.

**Comment by blakeembrey** [comment]
@Qix- Is there a common use-case where making a special case for this is worth it? It'd make it a bit confusing for anyone briefly reading the docs and it's not that hard to do `args.x.filter(x => x).length` (though obviously more verbose).

In any case, shouldn't `type()` always be called? I was just reading the code and I'd expect something like `-x false` to work (in case the default is `true` in code).

**Comment by blakeembrey** [comment]
@Qix- I see. Thoughts on using an internal `boolean` symbol instead (e.g. `export const Positional = Symbol('positional')` (or even `'__POSITIONAL__'` for older systems)? I'm just thinking about how this from documentation in the README and TypeScript. In terms of TypeScript, it'd require an overload in either case to override `Boolean` behaviour when the numeric is introduced so feel free to ping me then.

If you use an internal symbol, would it make sense to just always be a number? I don't think I'd really care about `true` or `false` if it can never be `false` anyway.

**Comment by Qix-** [comment]
I'm not sure what problem the boolean symbol would solve. Could you explain a bit more?

As well, perhaps I'm missing something, but `[Boolean]` argument types are always numbers.

**Comment by blakeembrey** [comment]
@Qix- Just API consistency. Right now things are super easy to understand, and there's no documentation on `Boolean` really needed (even though it is special). After this, in either case, you need to write documentation on the new special behavior. I just thought it was more consistent to introduce a new behavior instead of a change to special case to existing statements. E.g. this statement is false now:

> This means the built-in String, Number, and Boolean type constructors "just work" as type functions.

Whereas just adding a new sentence mentioning positional flags is easy:

```js
arg({
  '-x': arg.POS,
  '-y': [arg.POS]
})
```

To be honest, I'm don't feel too strongly either way. I just get a little worried when I see implicit over explicit behavior of inputs since it requires people to "know" this is special and changes behavior. Imagine coming onto a new project and always explaining that `[Boolean]` actually produces a number. But, you know, everything else is true to the statement above.

**Comment by rauchg** [comment]
I agree with @blakeembrey – I'd argue it's **elegant** to maintain type affinity. The number result is very _surprising_ when the "type definition" is `[Boolean]`

**Comment by blakeembrey** [comment]
@Qix- I do agree by the way! How do you feel about the constant instead of overloading the built-in `Boolean` function? Is there a name for this behavior? It could just be:

```js
arg({
  '-x': arg.BOOL // `arg.COUNT`, `arg.POS`, `arg.SEEN`, `arg.EXISTS`, `arg.<name of behavior>`
})
```

I just noticed the third argument too:

> The previous value for the destination (useful for reduce-like operatons or for supporting -v multiple times, etc.)

This could be supported by providing `arg.COUNT` which takes over `Boolean` and does `(_, _, i = 0) => i + 1`.

**Comment by blakeembrey** [comment]
@Qix- That's a good point. In that case, array support is just which might make that case easier:

```js
function of (value, argName, prev = []) {
  prev.push(value)
  return prev
}

arg({
  '-x': of(String)
})
```

**Comment by Qix-** [comment]
@blakeembrey Right, but that means losing the simplicity of `[Type]`.

Existing code would have to migrate to something like:

```javascript
const arg = require('arg');

const args = arg({
    '--include': arg.ARRAY(String),
    '-I': '--include'
});
```

For comparison, the existing spec which is simpler to write looks like:

```javascript
const args = arg({
    '--include': [String],
    '-I': '--include'
});
```

**Comment by pacocoursey** [comment]
If we want to keep the simplicity of `[Type]` but avoid the redundancy of returning an array that will only ever contain `true` values, how about faking it by using `[Boolean].length`?

This correctly specifies that a number will be returned, and looking at the code correctly implicates that it will return the length of the boolean array. It feels like a hack (and you could just type `1` instead of `[Boolean].length`) but it would work. Thoughts?

```js
// ./my-program -vv -xxx

const args = arg({
    '-v': [Boolean].length,
    '-x': [Boolean]
});

/*
{
    '-v': 2,
    '-x': [true, true, true]
}
*/
```

**Comment by Qix-** [comment]
That feels like a hack :/ I'd say -1 on it.

I still think the symbol and helper method is the way to go.
