### ISSUE TITLE
Separate `--` and `_` arguments

### ISSUE THREAD

**Issue by blakeembrey** [zeit/arg#30]
I need the ability to get `_` arguments and `--` separately. Currently everything after `--` gets placed into `args._` so I can't tell which was after the `--` argument or which was part of the command. This is required to use in projects such as https://github.com/Qard/onchange.

**Comment by Qix-** [comment]
I'm :-1: on this, this isn't how `--` is supposed to work. Seems like you're trying to fix an XY problem - can you expand a bit on what you're trying to do by splitting the parsed arguments?

**Comment by blakeembrey** [comment]
@Qix- It's how the library works: https://github.com/Qard/onchange.

**Comment by blakeembrey** [comment]
I would, of course,  be open to hear how this should work instead of how it does work. But since this is an existing library and existing feature in other libraries like `minimist` it would be nice to have - even if you say it shouldn't be done.

**Comment by Qix-** [comment]
I don't like the argument of "other libraries do it, therefore..." because a lot of other libraries have large scopes in order to make everyone that has a niche use case happy 😅 Which is a large reason why `arg` was written..

For what it's worth, this pattern of option parsing isn't common in the UNIX world.

Some examples of programs that tackle this in different ways are:

- `xargs`, which treats the first positional as the beginning of the command
- `find`, which uses `-exec` and a subsequent `\;` to denote the beginning and end of a command to run against each found entry
- `entr`, which reads a file listing from standard input

`--` is the canonical way to say "stop reading the rest of the CLI as options/flags and treat them as positionals". That is the mental contract users have when using CLI's.

---

The only way I'd be comfortable handling this is to have an option `stopAtDashes: true` or something like that, akin to `stopAtPositional`. But I feel strongly against having a separate array for arguments.

**Comment by Qix-** [comment]
Yeah I'm trying to think of how this could be added in a generally GNU-ish way but I can't think of anything that doesn't introduce yet another option. :/ It's a real edge case IMO, I don't see many programs use `--` as a major delimiter.

> Also, for the `find` style behaviour, there's no way to do this in arg today. Do you want to try and support this somehow?

Not really, no - their flags are positional as well, and they use single hyphens for long flags. It's an entirely different parsing scheme that would more than likely be easier to implement in a custom manner - definitely out of scope for `arg`.

**Comment by Qix-** [comment]
Actually, a new option might be okay in this case:

```javascript
{
   literalDashes: true
}
```

That would cause `--` to be treated as a positional, allowing you to split `._` how you'd like. It would also solve a few other use-cases as well.

**Comment by blakeembrey** [comment]
This might work but it’s still an incompatible change for `onchange` since there’s no specific order required today for the patterns and CLI args. I don’t think it’s incompable with this suggestion either so I don’t think I should block you if it helps other cases!

**Comment by Qix-** [comment]
Could you explain your use case then? With the change in #35, you can achieve what you want here in this ticket.

**Comment by blakeembrey** [comment]
@Qix- It's not compatible because `onchange "**/*.ts" -k -- npm start` would mean something else in #35 compared to #33.

**Comment by Qix-** [comment]
No, #35 doesn't stop parsing. It just includes `--` in the `._` array instead of treating it specially.

In `onchange`, what I would personally do is just to `.slice()` based on `process.argv` since it's a really niche use-case, and then just run the first of the two arrays through `arg`.

**Comment by blakeembrey** [comment]
@Qix- Sure, that makes sense 👍
